amcl:
  ros__parameters:
    use_sim_time: false

    # frame names
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map

    # sensor topics
    scan_topic: scan

    # initial pose
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0

    # tuning
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.2

